export const allresearch = [
    {
        id: 1,
        research:'Banking',
        researchname: 'Shareholder Bargaining Power, Debt Overhang, and Investment',
        researchwebsite: 'https://academic.oup.com/rcfs/article-abstract/7/2/276/5056934',
        author1: 'Sudheer Chava',
        author2: 'Emmanuel Alanis',
        author3: 'Praveen Kumar',
        author4: '',
        author5: '',
        author1website: 'https://www.scheller.gatech.edu/directory/faculty/chava/index.html',
        author2website: '',
        author3website: '',
        author4website: '',
        author5website: '',
        image1:'/images/Nikhil_12.jpg',
        image2:'/images/Nikhil_13.jpg',
        image3:'/images/Nikhil_12.jpg',
        image4:'/images/Nikhil_13.jpg',
        image5:'/images/Nikhil_12.jpg',
        abstract:"Using a dynamic model of strategic bargaining between equity and debt holders following default, we analyze the impact of shareholder bargaining power and debt overhang on optimal investment and strategic default. Our empirical tests utilize a new measure of the debt overhang wedge based on default probabilities generated from a hazard model for bankruptcy. Consistent with the theoretical predictions, bondholder (shareholder) ownership concentration ceteris paribus enhances (weakens) the overhang wedge and dampens (increases) capital investment. We identify novel ownership-structure-related factors in firm-level capital investment and document how post-default shareholder bargaining power alleviates the underinvestment problem caused by debt overhang.",
        keytakeaway:"We identify novel ownership-structure-related factors in firm-level capital investment and document how post-default shareholder bargaining power alleviates the underinvestment problem caused by debt overhang."
    },
    {
        id: 2,
        research:'Banking',
        researchname: 'The Dynamics of Borrower Reputation Following Financial Misreporting',
        researchwebsite: 'https://pubsonline.informs.org/doi/10.1287/mnsc.2017.2739',
        author1: 'Sudheer Chava',
        author2: 'Kershen Huang',
        author3: 'Shane A. Johnson',
        author4: '',
        author5: '',
        author1website: 'https://www.scheller.gatech.edu/directory/faculty/chava/index.html',
        author2website: 'https://pubsonline.informs.org/action/doSearch?text1=Huang%2C+Kershen&field1=Contrib',
        author3website: 'https://pubsonline.informs.org/action/doSearch?text1=Johnson%2C+Shane+A&field1=Contrib',
        author4website: '',
        author5website: '',
        image1:'/images/Nikhil_12.jpg',
        image2:'/images/Nikhil_13.jpg',
        image3:'/images/Nikhil_12.jpg',
        image4:'/images/Nikhil_13.jpg',
        image5:'/images/Nikhil_12.jpg',
        abstract:'We study the dynamics of borrower reputation in bank loan markets following revelations of financial misreporting by the borrower. Misreporting firms pay greater loan spreads than matched firms for at least six years following revelation of the misreporting, and there is no evidence of a downward trend in the misreporting premium. Following revelation, misreporting firms are more likely to engage in various actions to potentially rebuild their reputations, but even firms that engage in multiple actions continue to pay greater loan spreads for at least six years. Our results suggest that misreporting causes long-lasting and costly reputation losses that firms find very difficult or prohibitively costly to restore. This paper was accepted by Wei Jiang, finance.',
        keytakeaway:"Our results suggest that misreporting causes long-lasting and costly reputation losses that firms find very difficult or prohibitively costly to restore."
    }
]